---
# Task skipped if repositories as been updated less than 86400sec = 24h
- name: Install system packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - build-essential
    - curl
    - python-software-properties
    - telnet
    - unzip
    - wget

- name: Install extra packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items: sys_packages
