mgate_user_lister:
    pattern:  /user/lister
    defaults: { _controller: mgateUserBundle:Default:lister }

mgate_user_voir:
    pattern:  /user/voir/{id}
    defaults: { _controller: mgateUserBundle:Default:voir }

mgate_user_modifier:
    pattern:  /user/modifier/{id}
    defaults: { _controller: mgateUserBundle:Default:modifier }

mgate_user_supprimer:
    pattern:  /user/supprimer/{id}
    defaults: { _controller: mgateUserBundle:Default:delete }


mgate_user_addFromPersonne:
    pattern: /user/addFromPersonne/{id}
    defaults: { _controller: mgateUserBundle:Default:addUserFromPersonne }

