---
- name: Correct files permission
  file: path={{ item.path }} owner={{ item.owner }} recurse=yes state=directory
  with_items:
    - path:  /var/www/{{ symfony_src_dir }}
      owner: "{{ symfony_owner }}"
    - path:  /var/www/{{ symfony_src_dir }}/app/cache
      owner: www-data
    - path:  /var/www/{{ symfony_src_dir }}/app/logs
      owner: www-data

- name: Install composer dependencies
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && composer install
  ignore_errors: true

- name:  Create database
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && php app/console doctrine:database:create
  register: database_result
  ignore_errors: true

- name:  Create database schema
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && php app/console doctrine:schema:create
  when:  database_result|success
  ignore_errors: true

- name:  Update database schema
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && php app/console doctrine:schema:update --force
  when:  database_result|failed
  register: database_schema
  ignore_errors: true

- name: Drop database and recreate it
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && php app/console doctrine:schema:create
    && php app/console doctrine:schema:create
  when: database_schema|failed
  ignore_errors: true

- name:  Reload fixtures
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && php app/console doctrine:fixtures:load
  ignore_errors: true
