---
- name: Install nginx
  sudo: yes
  apt:  pkg=nginx state=latest

- name:     Ensure nginx is configured
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf group=root owner=root
  notify:   Reload nginx

- name:   Configure nginx vhost
  sudo:   yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: Reload nginx

