---
- name:  Install Composer globally
  sudo:  yes
  shell: >
    curl -sS https://getcomposer.org/installer | php
    && mv composer.phar {{ composer_path }}

- name:  Update Composer to latest version
  sudo:  yes
  shell: composer self-update # Does not require the path since is installed globaly
